<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class CovidHistory extends Model
{
    use HasFactory;

    protected $fillable = [

'counting_date',
'korea_totalCnt',
'korea_recCnt',
'korea_deathCnt',
'korea_isolCnt',
'korea_qurRate',
'korea_incDec',
'korea_incDecK',
'korea_incDecF',

'seoul_totalCnt',
'seoul_recCnt',
'seoul_deathCnt',
'seoul_isolCnt',
'seoul_qurRate',
'seoul_incDec',
'seoul_incDecK',
'seoul_incDecF',

'busan_totalCnt',
'busan_recCnt',
'busan_deathCnt',
'busan_isolCnt',
'busan_qurRate',
'busan_incDec',
'busan_incDecK',
'busan_incDecF',

'daegu_totalCnt',
'daegu_recCnt',
'daegu_deathCnt',
'daegu_isolCnt',
'daegu_qurRate',
'daegu_incDec',
'daegu_incDecK',
'daegu_incDecF',

'incheon_totalCnt',
'incheon_recCnt',
'incheon_deathCnt',
'incheon_isolCnt',
'incheon_qurRate',
'incheon_incDec',
'incheon_incDecK',
'incheon_incDecF',

'gwangju_totalCnt',
'gwangju_recCnt',
'gwangju_deathCnt',
'gwangju_isolCnt',
'gwangju_qurRate',
'gwangju_incDec',
'gwangju_incDecK',
'gwangju_incDecF',

'daejeon_totalCnt',
'daejeon_recCnt',
'daejeon_deathCnt',
'daejeon_isolCnt',
'daejeon_qurRate',
'daejeon_incDec',
'daejeon_incDecK',
'daejeon_incDecF',

'ulsan_totalCnt',
'ulsan_recCnt',
'ulsan_deathCnt',
'ulsan_isolCnt',
'ulsan_qurRate',
'ulsan_incDec',
'ulsan_incDecK',
'ulsan_incDecF',

'sejong_totalCnt',
'sejong_recCnt',
'sejong_deathCnt',
'sejong_isolCnt',
'sejong_qurRate',
'sejong_incDec',
'sejong_incDecK',
'sejong_incDecF',

'gyeonggi_totalCnt',
'gyeonggi_recCnt',
'gyeonggi_deathCnt',
'gyeonggi_isolCnt',
'gyeonggi_qurRate',
'gyeonggi_incDec',
'gyeonggi_incDecK',
'gyeonggi_incDecF',

'gangwon_totalCnt',
'gangwon_recCnt',
'gangwon_deathCnt',
'gangwon_isolCnt',
'gangwon_qurRate',
'gangwon_incDec',
'gangwon_incDecK',
'gangwon_incDecF',

'chungbuk_totalCnt',
'chungbuk_recCnt',
'chungbuk_deathCnt',
'chungbuk_isolCnt',
'chungbuk_qurRate',
'chungbuk_incDec',
'chungbuk_incDecK',
'chungbuk_incDecF',

'chungnam_totalCnt',
'chungnam_recCnt',
'chungnam_deathCnt',
'chungnam_isolCnt',
'chungnam_qurRate',
'chungnam_incDec',
'chungnam_incDecK',
'chungnam_incDecF',

'jeonbuk_totalCnt',
'jeonbuk_recCnt',
'jeonbuk_deathCnt',
'jeonbuk_isolCnt',
'jeonbuk_qurRate',
'jeonbuk_incDec',
'jeonbuk_incDecK',
'jeonbuk_incDecF',

'jeonnam_totalCnt',
'jeonnam_recCnt',
'jeonnam_deathCnt',
'jeonnam_isolCnt',
'jeonnam_qurRate',
'jeonnam_incDec',
'jeonnam_incDecK',
'jeonnam_incDecF',

'gyeongbuk_totalCnt',
'gyeongbuk_recCnt',
'gyeongbuk_deathCnt',
'gyeongbuk_isolCnt',
'gyeongbuk_qurRate',
'gyeongbuk_incDec',
'gyeongbuk_incDecK',
'gyeongbuk_incDecF',

'gyeongnam_totalCnt',
'gyeongnam_recCnt',
'gyeongnam_deathCnt',
'gyeongnam_isolCnt',
'gyeongnam_qurRate',
'gyeongnam_incDec',
'gyeongnam_incDecK',
'gyeongnam_incDecF',

'jeju_totalCnt',
'jeju_recCnt',
'jeju_deathCnt',
'jeju_isolCnt',
'jeju_qurRate',
'jeju_incDec',
'jeju_incDecK',
'jeju_incDecF',


    ];
}
